/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gympos.view;

import gympos.model.Cliente;
import gympos.model.ExcepcionDatos;
import gympos.model.Membresia;
import gympos.model.TipoMembresia;
import gympos.service.ClienteService;
import gympos.service.MembresiaService;
import java.math.BigDecimal; // Necesario para el descuento (asumiendo BigDecimal.ZERO)
import java.time.LocalDate;  // Necesario para la fecha de inicio
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel; // Para manejar el JComboBox
import javax.swing.JOptionPane;
/**
 *
 * @author ferma
 */
public class AddMembresiaEditClientesView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddMembresiaEditClientesView.class.getName());

    // CAMPOS CLAVE
    private final Cliente clienteAEditar;
    private final EditClientesView parentView;
    private final ClienteService clienteService;
    private final MembresiaService membresiaService;
    private List<TipoMembresia> tiposMembresiaDisponibles; // Almacena los objetos TipoMembresia
    
    /**
     * CONSTRUCTOR MODIFICADO
     * Creates new form AddMembresiaEditClientesView
     * @param cliente Cliente al que se le va a agregar la membresía.
     * @param parent Referencia a la vista padre para el refresco.
     */
    public AddMembresiaEditClientesView(Cliente cliente, EditClientesView parent) {
        initComponents();
        this.clienteAEditar = cliente;
        this.parentView = parent;
        this.clienteService = new ClienteService(); 
        this.membresiaService = new MembresiaService();
        
        cargarOpcionesMembresias(); // Llamada para llenar el JComboBox
        
        // Opcional: Asignar el nombre del cliente al título para contexto
        this.setTitle("Agregar Membresía a: " + cliente.getNombre() + " " + cliente.getApellido());
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonRegresar = new javax.swing.JButton();
        AgregarMembresiaCliente = new javax.swing.JButton();
        OpcionesMembresias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescuento = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonRegresar.setBackground(new java.awt.Color(176, 178, 255));
        BotonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        AgregarMembresiaCliente.setBackground(new java.awt.Color(167, 207, 144));
        AgregarMembresiaCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarMembresiaCliente.setText("Agregar");
        AgregarMembresiaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMembresiaClienteActionPerformed(evt);
            }
        });

        OpcionesMembresias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OpcionesMembresias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OpcionesMembresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesMembresiasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Membresias Disponibles:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Descuento Personalizado:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("%");

        jScrollPane1.setViewportView(txtDescuento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OpcionesMembresias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(AgregarMembresiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addComponent(BotonRegresar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OpcionesMembresias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarMembresiaCliente)
                    .addComponent(BotonRegresar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        // 1. Cierra la ventana actual de Agregar Membresía.
        this.dispose();
        
        // 2. Asegura que la ventana padre (EditClientesView) se traiga al frente y recupere el foco.
        if (parentView != null) {
            parentView.toFront(); 
            // Opcional: si la vista padre se hubiera ocultado, usaríamos parentView.setVisible(true);
        }
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void AgregarMembresiaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMembresiaClienteActionPerformed

        // 1. Validar selección
        String nombreTipoSeleccionado = (String) OpcionesMembresias.getSelectedItem();
        if (nombreTipoSeleccionado == null || nombreTipoSeleccionado.contains("No hay")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de membresía válido.", "Error de Datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // 2. Obtener el objeto TipoMembresia completo de la lista local
            Optional<TipoMembresia> tipoOpt = tiposMembresiaDisponibles.stream()
                .filter(t -> t.getNombre().equals(nombreTipoSeleccionado))
                .findFirst();

            if (!tipoOpt.isPresent()) {
                // Este caso no debería ocurrir si cargarOpcionesMembresias funciona correctamente
                throw new ExcepcionDatos("Error interno: El tipo de membresía seleccionado no fue encontrado.");
            }
            
            TipoMembresia tipoSeleccionado = tipoOpt.get();
            
            // --- Parámetros para la nueva Membresia ---
            // El ID debe ser generado por el servicio para asegurar unicidad
            String nuevoId = membresiaService.generarNuevoIdMembresia(); 
            LocalDate fechaInicio = LocalDate.now();
            BigDecimal descuento = BigDecimal.ZERO;
            String descuentoText = txtDescuento.getText().trim();
            
            if (!descuentoText.isEmpty()) {
                try {
                    // Intentar parsear el texto a un número (puede ser entero o decimal)
                    BigDecimal valorIngresado = new BigDecimal(descuentoText);

                    // Validar que el valor sea >= 0 y <= 100
                    if (valorIngresado.compareTo(BigDecimal.ZERO) < 0 || valorIngresado.compareTo(new BigDecimal("100")) > 0) {
                        JOptionPane.showMessageDialog(this, "El descuento debe ser un valor numérico entre 0 y 100.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    // Convertir el porcentaje (X) a un factor (X/100)
                    descuento = valorIngresado.divide(new BigDecimal("100.00"), 4, BigDecimal.ROUND_HALF_UP);

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "El descuento debe ser un valor numérico válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            // 3. Crear el nuevo objeto Membresia
            Membresia nuevaMembresia = new Membresia(nuevoId, tipoSeleccionado, fechaInicio, descuento);
            
            // 4. Agregar la membresía al cliente
            clienteAEditar.getMembresias().add(nuevaMembresia);
            
            // 5. Persistir los cambios del cliente
            clienteService.actualizarCliente(clienteAEditar);
            
            // 6. Refrescar la vista padre (EditClientesView)
            parentView.refrescarMembresias();
            
            // 7. Mostrar éxito y cerrar ventana
            JOptionPane.showMessageDialog(this, 
                "Membresía '" + tipoSeleccionado.getNombre() + "' agregada a " + clienteAEditar.getNombre() + ".", 
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            
        } catch (ExcepcionDatos ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al agregar membresía", ex);
            JOptionPane.showMessageDialog(this, 
                "Error al agregar la membresía: " + ex.getMessage(), 
                "Error de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
             logger.log(java.util.logging.Level.SEVERE, "Error inesperado", ex);
             JOptionPane.showMessageDialog(this, 
                "Error inesperado: " + ex.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AgregarMembresiaClienteActionPerformed

    private void OpcionesMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesMembresiasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OpcionesMembresiasActionPerformed
    
    private void cargarOpcionesMembresias() {
        try {
            // 1. Obtener la lista de TiposMembresia del servicio
            this.tiposMembresiaDisponibles = membresiaService.getTiposMembresia();
            
            // 2. Crear un modelo para el JComboBox
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            
            if (tiposMembresiaDisponibles.isEmpty()) {
                model.addElement("No hay Tipos de Membresía disponibles");
                AgregarMembresiaCliente.setEnabled(false);
            } else {
                // 3. Agregar solo el nombre de cada TipoMembresia al modelo
                for (TipoMembresia tipo : tiposMembresiaDisponibles) {
                    model.addElement(tipo.getNombre());
                }
            }
            
            // 4. Asignar el modelo al JComboBox
            OpcionesMembresias.setModel(model);
            
        } catch (Exception ex) {
             logger.log(java.util.logging.Level.SEVERE, "Error al cargar tipos de membresía", ex);
             JOptionPane.showMessageDialog(this, 
                 "Error al cargar los tipos de membresía: " + ex.getMessage(), 
                 "Error de Carga", JOptionPane.ERROR_MESSAGE);
             AgregarMembresiaCliente.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AddMembresiaEditClientesView(parentview.clienteAEditar,this).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarMembresiaCliente;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JComboBox<String> OpcionesMembresias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtDescuento;
    // End of variables declaration//GEN-END:variables
}
