/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gympos.view;

import gympos.model.Cliente; // <--- AGREGAR
import gympos.service.ClienteService;
import java.util.List; // <--- AGREGAR
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; // <--- AGREGAR
/**
 *
 * @author ferma
 */
public class ClientesView extends javax.swing.JFrame
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientesView.class.getName());
    private final ClienteService clienteService; 
    private DefaultTableModel tableModel; // <--- AGREGAR: Modelo de datos para la tabla

    private final String[] COLUMNAS = {"ID", "Nombre", "Apellido", "Email", "Puntos"}; // <--- AGREGAR

    /**
     * Creates new form ClientesView
     */
    public ClientesView() {
        initComponents();
        this.clienteService = new ClienteService(); 

        // Inicializar el modelo de la tabla
        this.tableModel = new DefaultTableModel(COLUMNAS, 0); // 0 filas iniciales
        jTable1.setModel(this.tableModel); // Asignar el modelo a la jTable1

        // Cargar los datos al inicializar la vista
        cargarTodosLosClientes(); // <--- AGREGAR llamada al método
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarUser = new javax.swing.JButton();
        BuscarUser = new javax.swing.JButton();
        ModificarUser = new javax.swing.JButton();
        EliminarUser = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AgregarUser.setText("Agregar Cliente");
        AgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUserActionPerformed(evt);
            }
        });

        BuscarUser.setText("Buscar Cliente");
        BuscarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUserActionPerformed(evt);
            }
        });

        ModificarUser.setText("Modificar Cliente");
        ModificarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUserActionPerformed(evt);
            }
        });

        EliminarUser.setText("Eliminar Cliente");
        EliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUserActionPerformed(evt);
            }
        });

        BotonRegresar.setBackground(new java.awt.Color(176, 178, 255));
        BotonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonRegresar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarUser)
                            .addComponent(ModificarUser)
                            .addComponent(AgregarUser)
                            .addComponent(BuscarUser))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(AgregarUser)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarUser)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarUser)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(BotonRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUserActionPerformed
        // TODO add your handling code here:
        // 1. Pedir al usuario el término de búsqueda mediante un cuadro de diálogo
        String query = JOptionPane.showInputDialog(this, 
            "Ingrese el nombre o apellido a buscar:", 
            "Buscar Cliente", 
            JOptionPane.QUESTION_MESSAGE);
        
        // 2. Validar la entrada (si cancela o deja vacío)
        if (query == null || query.trim().isEmpty()) {
            // Si cancela o no ingresa nada, cargamos todos los clientes
            cargarTodosLosClientes();
            return;
        }
        
        // 3. Realizar la búsqueda usando ClienteService
        // El método buscarClientes busca por nombre o apellido (simula una búsqueda parcial)
        List<Cliente> resultados = clienteService.buscarClientes(query.trim());
        
        // 4. Actualizar la tabla con los resultados
        actualizarTabla(resultados);
        
        // 5. Mostrar un mensaje si no se encuentran resultados
        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "No se encontraron clientes que coincidan con la búsqueda: " + query.trim(), 
                "Búsqueda sin resultados", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BuscarUserActionPerformed

    private void ModificarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUserActionPerformed
        String idCliente = obtenerIdClienteSeleccionado();
        
        if (idCliente == null) {
            return;
        }
        
        java.util.Optional<gympos.model.Cliente> clienteOpt = clienteService.obtenerClientePorId(idCliente);
        
        if (clienteOpt.isPresent()) 
        {
            gympos.model.Cliente clienteAEditar = clienteOpt.get();
            
            // 1. Instanciar EditClientesView: Pasamos el Cliente y la referencia de la vista padre
            EditClientesView editView = new EditClientesView(clienteAEditar, this); 
            editView.setVisible(true);
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, 
                "Error: No se pudo encontrar el cliente para modificar.", 
                "Error Interno", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ModificarUserActionPerformed

    private void EliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUserActionPerformed
        // TODO add your handling code here:
        String idCliente = obtenerIdClienteSeleccionado();
        
        if (idCliente == null) {
            return; // Ya se mostró el mensaje de error de selección
        }
        
        // Confirmación antes de eliminar
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar al cliente con ID: " + idCliente + "?", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) 
        {
            try 
            {
                // Llamada al servicio para eliminar
                clienteService.eliminarCliente(idCliente);
                
                // Refrescar la tabla
                cargarTodosLosClientes(); 
                
                JOptionPane.showMessageDialog(this, 
                    "Cliente " + idCliente + " eliminado exitosamente.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
            } 
            catch (gympos.model.ExcepcionDatos ex) 
            {
                JOptionPane.showMessageDialog(this, 
                    "Error al eliminar el cliente: " + ex.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_EliminarUserActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        new MainApp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void AgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUserActionPerformed
        // TODO add your handling code here:
        new AddClientesView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarUserActionPerformed
    
    // Después del constructor y antes del main

    private void cargarTodosLosClientes() 
    {
        List<Cliente> clientes = clienteService.getClientes();
        actualizarTabla(clientes);
    }
    
    private void actualizarTabla(List<Cliente> clientes)
    {
        // Limpiar filas anteriores
        this.tableModel.setRowCount(0);

        // Iterar sobre la lista de clientes y añadir cada uno como una fila
        for (Cliente cliente : clientes) 
        {
            Object[] fila = new Object[]{
                cliente.getIdCliente(),
                cliente.getNombre(),
                cliente.getApellido(),
                cliente.getEmail(),
                cliente.getPuntos()
            };

            this.tableModel.addRow(fila);
        }
    }
    
    public void refrescarTabla() {
        cargarTodosLosClientes();
    }
    
    /**
    * Obtiene el ID del cliente seleccionado en la tabla.
    * @return El ID del cliente, o null si no hay selección.
    */
   private String obtenerIdClienteSeleccionado() 
   {
       // Obtener el índice de la fila seleccionada
       int filaSeleccionada = jTable1.getSelectedRow();

       if (filaSeleccionada == -1) 
       {
           JOptionPane.showMessageDialog(this, 
               "Debe seleccionar un cliente de la tabla.", 
               "Error de Selección", 
               JOptionPane.WARNING_MESSAGE);
           return null;
       }

       // El ID se encuentra en la primera columna (índice 0)
       return (String) jTable1.getValueAt(filaSeleccionada, 0);
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientesView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUser;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton BuscarUser;
    private javax.swing.JButton EliminarUser;
    private javax.swing.JButton ModificarUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
