/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gympos.view;

import gympos.model.Cliente; // <--- AGREGAR
import gympos.model.ExcepcionDatos;
import gympos.model.Membresia;
import gympos.service.ClienteService;
import gympos.service.MembresiaService;
import java.util.List; // <--- AGREGAR
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferma
 */
public class EditClientesView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditClientesView.class.getName());
    private final ClienteService clienteService;
    private final MembresiaService membresiaService;
    private DefaultTableModel tableModel; 
    
    // CAMPOS CLAVE
    private Cliente clienteAEditar;      // Cliente que se está editando
    private ClientesView parentView;     // Referencia a la vista padre
    
    private final String[] COLUMNAS_MEMBRESIAS = {"ID", "Tipo", "Inicio", "Fin", "Precio Pagado", "Activa"}; 
    
    // CONSTRUCTOR MODIFICADO
    public EditClientesView(Cliente cliente, ClientesView parent) {
        initComponents();
        this.clienteService = new ClienteService(); 
        this.membresiaService = new MembresiaService(); 
        
        // ASIGNAR CLIENTE Y VISTA PADRE
        this.clienteAEditar = cliente;
        this.parentView = parent;

        // Inicializar el modelo de la tabla de Membresías
        this.tableModel = new DefaultTableModel(COLUMNAS_MEMBRESIAS, 0); 
        jTable1.setModel(this.tableModel); 
        
        // CARGAR DATOS
        cargarDatosCliente();      // Cargar campos de texto
        cargarMembresiasCliente(); // Cargar tabla de membresías
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        ModificarCliente = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CantPuntos = new javax.swing.JTextField();
        AgregarMembresia = new javax.swing.JButton();
        EliminarMembresia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Email:");

        ModificarCliente.setBackground(new java.awt.Color(167, 207, 144));
        ModificarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModificarCliente.setText("Modificar");
        ModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarClienteActionPerformed(evt);
            }
        });

        BotonRegresar.setBackground(new java.awt.Color(176, 178, 255));
        BotonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad de Puntos:");

        jLabel6.setText("Membresias Activas:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        CantPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantPuntosActionPerformed(evt);
            }
        });

        AgregarMembresia.setText("Agregar Membresia");
        AgregarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMembresiaActionPerformed(evt);
            }
        });

        EliminarMembresia.setText("Eliminar Membresia");
        EliminarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMembresiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtApellido)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CantPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap(413, Short.MAX_VALUE)
                            .addComponent(EliminarMembresia))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(411, Short.MAX_VALUE)
                            .addComponent(AgregarMembresia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CantPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModificarCliente)
                            .addComponent(BotonRegresar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(AgregarMembresia)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarMembresia)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarClienteActionPerformed

        // 1. Validar Campos
        String newName = txtNombre.getText().trim();
        String newLastName = txtApellido.getText().trim();
        String newEmail = txtEmail.getText().trim();
        
        if (newName.isBlank() || newLastName.isBlank() || newEmail.isBlank())
        {
            JOptionPane.showMessageDialog(this, 
                "Los campos de Nombre, Apellido y Email son obligatorios.",
                "Error de Validación", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Validar Puntos (manejo de errores de conversión)
        int newPuntos = 0;
        try {
            newPuntos = Integer.parseInt(CantPuntos.getText().trim());
            if (newPuntos < 0) {
                 throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Los Puntos deben ser un número entero no negativo.",
                "Error de Validación", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 3. Actualizar el objeto Cliente con los nuevos datos
        clienteAEditar.setNombre(newName);
        clienteAEditar.setApellido(newLastName);
        clienteAEditar.setEmail(newEmail);
        clienteAEditar.setPuntos(newPuntos); 

        // 4. Persistir la actualización
        try {
            clienteService.actualizarCliente(clienteAEditar);
            
            JOptionPane.showMessageDialog(this, 
                "Cliente " + clienteAEditar.getIdCliente() + " modificado exitosamente.",
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // 5. Notificar a la vista padre y cerrar
            if (parentView != null) {
                parentView.refrescarTabla(); 
            }
            this.dispose(); // Cierra la ventana de edición

        } catch (ExcepcionDatos ex) {
            JOptionPane.showMessageDialog(this, 
                "Error al modificar el cliente: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ModificarClienteActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        new ClientesView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void CantPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantPuntosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CantPuntosActionPerformed

    private void EliminarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMembresiaActionPerformed
        // TODO add your handling code here:
        String idMembresia = obtenerIdMembresiaSeleccionada();

        if (idMembresia == null) {
            return; // El método auxiliar ya mostró el mensaje de error.
        }

        // Confirmación antes de eliminar
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea eliminar la membresía " + idMembresia + "?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) 
        {
            try {
                // 1. Remover la membresía del objeto Cliente
                boolean removido = clienteAEditar.getMembresias()
                                    .removeIf(m -> m.getIdMembresia().equals(idMembresia));

                if (removido) {
                    // 2. Persistir los cambios del cliente en el servicio
                    clienteService.actualizarCliente(clienteAEditar);

                    // 3. Refrescar la tabla en esta vista y en la vista principal
                    refrescarMembresias(); 

                    JOptionPane.showMessageDialog(this,
                        "Membresía " + idMembresia + " eliminada exitosamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                     JOptionPane.showMessageDialog(this,
                        "Error: No se encontró la membresía con ID: " + idMembresia,
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (gympos.model.ExcepcionDatos ex) {
                JOptionPane.showMessageDialog(this,
                    "Error al eliminar la membresía: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_EliminarMembresiaActionPerformed

    private void AgregarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMembresiaActionPerformed
        // TODO add your handling code here:
        new AddMembresiaEditClientesView(clienteAEditar,this).setVisible(true);
    }//GEN-LAST:event_AgregarMembresiaActionPerformed

    private void cargarDatosCliente() {
        if (clienteAEditar != null) {
            txtNombre.setText(clienteAEditar.getNombre());
            txtApellido.setText(clienteAEditar.getApellido());
            txtEmail.setText(clienteAEditar.getEmail());
            // CantPuntos asume que es el JTextField para los puntos
            CantPuntos.setText(String.valueOf(clienteAEditar.getPuntos()));

            this.setTitle("Editar Cliente: " + clienteAEditar.getIdCliente());
        }
    }

    /**
     * Carga las membresías del cliente en la jTable1.
     */
    private void cargarMembresiasCliente() {
        if (clienteAEditar == null) return;

        this.tableModel.setRowCount(0); // Limpiar

        List<Membresia> membresias = clienteAEditar.getMembresias();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        for (Membresia m : membresias) 
        {
            Object[] fila = new Object[]{
                m.getIdMembresia(),
                m.getTipo().getNombre(),
                m.getFechaInicio().format(formatter),
                m.getFechaFin().format(formatter),
                m.getPrecioPagado().toString(),
                m.estaActiva() ? "Sí" : "No" // Determina si la membresía está activa
            };

            this.tableModel.addRow(fila);
        }
    }
    
    public void refrescarMembresias() {
        cargarMembresiasCliente();

        // Notificar a ClientesView para que refresque su tabla por si el estado 'Activa' del cliente cambió
        if (parentView != null) {
            parentView.refrescarTabla();
        }
    }
    
    /**
    * Obtiene el ID de la membresía seleccionada en la tabla.
    * @return El ID de la membresía (String), o null si no hay selección.
    */
   private String obtenerIdMembresiaSeleccionada() 
   {
       // Obtener el índice de la fila seleccionada
       int filaSeleccionada = jTable1.getSelectedRow();

       if (filaSeleccionada == -1) 
       {
           JOptionPane.showMessageDialog(this, 
               "Debe seleccionar una membresía de la tabla.", 
               "Error de Selección", 
               JOptionPane.WARNING_MESSAGE);
           return null;
       }

       // El ID se encuentra en la primera columna (índice 0)
       // Asumimos que la columna ID es de tipo String
       return (String) jTable1.getValueAt(filaSeleccionada, 0);
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new EditClientesView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarMembresia;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JTextField CantPuntos;
    private javax.swing.JButton EliminarMembresia;
    private javax.swing.JButton ModificarCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
