/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gympos.view;

import gympos.model.Empleado;
import gympos.service.AuthService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferma
 */
public class EmpleadosView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmpleadosView.class.getName());
    private final AuthService authService; 
    private DefaultTableModel tableModel; // <--- AGREGAR: Modelo de datos para la tabla

    private final String[] COLUMNAS = {"ID", "Usuario", "Password", "Rol"}; // <--- AGREGAR

    /**
     * Creates new form ClientesView
     */
    public EmpleadosView() {
        initComponents();
        this.authService = new AuthService(); 

        // Inicializar el modelo de la tabla
        this.tableModel = new DefaultTableModel(COLUMNAS, 0); // 0 filas iniciales
        jTable1.setModel(this.tableModel); // Asignar el modelo a la jTable1

        // Cargar los datos al inicializar la vista
        cargarDatosEmpleados(); // <--- AGREGAR llamada al método
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonRegresar2 = new javax.swing.JButton();
        AgregarUser = new javax.swing.JButton();
        BuscarUser = new javax.swing.JButton();
        ModificarUser = new javax.swing.JButton();
        EliminarUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonRegresar2.setBackground(new java.awt.Color(176, 178, 255));
        BotonRegresar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonRegresar2.setText("Regresar");
        BotonRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresar2ActionPerformed(evt);
            }
        });

        AgregarUser.setText("Agregar Empleado");

        BuscarUser.setText("Buscar Empleado");
        BuscarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUserActionPerformed(evt);
            }
        });

        ModificarUser.setText("Modificar Empleado");
        ModificarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUserActionPerformed(evt);
            }
        });

        EliminarUser.setText("Eliminar Empleado");
        EliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUserActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonRegresar2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModificarUser)
                            .addComponent(AgregarUser)
                            .addComponent(BuscarUser)
                            .addComponent(EliminarUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(AgregarUser)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarUser)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarUser)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarUser)))
                .addGap(32, 32, 32)
                .addComponent(BotonRegresar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresar2ActionPerformed
        // TODO add your handling code here:
        new MainApp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRegresar2ActionPerformed

    private void BuscarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarUserActionPerformed

    private void ModificarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarUserActionPerformed

    private void EliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarUserActionPerformed
    
    /**
     * Obtiene la lista de clientes y la carga en la jTable1.
     */
    private void cargarDatosEmpleados() 
    {
        // Limpiar filas anteriores
        this.tableModel.setRowCount(0);

        // Obtener la lista de clientes del servicio
        List<Empleado> empleados = authService.getEmpleados();

        // Iterar sobre la lista de clientes y añadir cada uno como una fila
        for (Empleado empleado : empleados) 
        {
            // Crear un array de objetos para representar la fila
            Object[] fila = new Object[]{
                empleado.getIdEmpleado(),
                empleado.getUsuario(),
                empleado.getPasswordHash(),
                empleado.getRol()
            };

            // Añadir la fila al modelo de la tabla
            this.tableModel.addRow(fila);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmpleadosView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUser;
    private javax.swing.JButton BotonRegresar2;
    private javax.swing.JButton BuscarUser;
    private javax.swing.JButton EliminarUser;
    private javax.swing.JButton ModificarUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
