/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gympos.view;

import gympos.model.Pago;
import gympos.model.Pago.MetodoPago;
import gympos.model.Empleado; 
import gympos.model.Membresia; 
import gympos.model.ExcepcionDatos;
import gympos.model.TipoMembresia;
import gympos.service.MembresiaService;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import gympos.model.Cliente; // <-- AGREGAR: Importar Cliente
import gympos.service.ClienteService; // <-- AGREGAR: Importar ClienteService
import java.util.List;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author ferma
 */
public class PagosView extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PagosView.class.getName());
    private final MembresiaService membresiaService;
    private final ClienteService clienteService; // <-- CAMBIO 1: Declarar ClienteService
    private Empleado empleadoEnSesion;
    /**
     * Creates new form PagosView
     */
    public PagosView(Empleado empleado) {
        initComponents();
        this.membresiaService = new MembresiaService();
        this.clienteService = new ClienteService();
        
        // **ACTUALIZACIÓN:** Asignar el empleado recibido del login
        if (empleado == null) {
            JOptionPane.showMessageDialog(this, "Error: Empleado no autenticado.", "Error de Sesión", JOptionPane.ERROR_MESSAGE);
        }
        this.empleadoEnSesion = empleado; 
        
        cargarClientesID(); 
        cargarMetodosPago();
        
        // <-- CAMBIO 4: Añadir el listener al ComboBox de Cliente ID -->
        opClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opClienteIDActionPerformed(evt);
            }
        });
        
        // Inicializar opMembresia vacío con valor por defecto
        ((DefaultComboBoxModel<String>) opMembresia.getModel()).removeAllElements();
        ((DefaultComboBoxModel<String>) opMembresia.getModel()).addElement("-- Seleccione Membresía --");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonPagar = new javax.swing.JButton();
        opMembresia = new javax.swing.JComboBox<>();
        opMetodoPago = new javax.swing.JComboBox<>();
        opClienteID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Método de Pago:");

        BotonRegresar.setBackground(new java.awt.Color(176, 178, 255));
        BotonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Procesamiento de pagos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ClienteID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Membresia a Pagar:");

        BotonPagar.setBackground(new java.awt.Color(167, 207, 144));
        BotonPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonPagar.setText("Pagar");
        BotonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagarActionPerformed(evt);
            }
        });

        opMembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        opMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMetodoPagoActionPerformed(evt);
            }
        });

        opClienteID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opClienteIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonPagar)
                                .addGap(43, 43, 43))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opClienteID, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addComponent(opMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(opMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonRegresar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(opMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(opMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(BotonPagar)))
                .addGap(12, 12, 12)
                .addComponent(BotonRegresar)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        new MainApp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagarActionPerformed
        // TODO add your handling code here:
        try {
            // 1. OBTENER Y VALIDAR LAS SELECCIONES DE LOS JCOMBOBOX

            String idClienteSeleccionado = (String) opClienteID.getSelectedItem();
            String membresiaCompletaSeleccionada = (String) opMembresia.getSelectedItem();
            String metodoPagoSeleccionado = (String) opMetodoPago.getSelectedItem();

            // Validar selección de Cliente
            if (idClienteSeleccionado == null || idClienteSeleccionado.contains("-- Seleccione Cliente --")) {
                throw new ExcepcionDatos("Debe seleccionar un cliente.");
            }

            // Validar selección de Membresía
            if (membresiaCompletaSeleccionada == null || membresiaCompletaSeleccionada.contains("-- Seleccione Membresía --")) {
                throw new ExcepcionDatos("Debe seleccionar una membresía.");
            }

            // Validar selección de Método de Pago
            if (metodoPagoSeleccionado == null || metodoPagoSeleccionado.contains("-- Seleccione Método --")) {
                throw new ExcepcionDatos("Debe seleccionar un método de pago.");
            }

            // 2. EXTRAER OBJETOS DE NEGOCIO A PARTIR DE LAS SELECCIONES

            // Extraer el ID de la Membresía (formato: [ID Membresía] - [Nombre Tipo] (..))
            String idMembresia = membresiaCompletaSeleccionada.substring(0, membresiaCompletaSeleccionada.indexOf(" - ")).trim();

            // Obtener el objeto Cliente completo (necesario para encontrar la Membresía)
            Cliente cliente = clienteService.obtenerClientePorId(idClienteSeleccionado)
                    .orElseThrow(() -> new ExcepcionDatos("Error: Cliente no encontrado con ID: " + idClienteSeleccionado));

            // Obtener el objeto Membresia completo
            Membresia membresiaAPagar = cliente.getMembresias().stream()
                    .filter(m -> m.getIdMembresia().equals(idMembresia))
                    .findFirst()
                    .orElseThrow(() -> new ExcepcionDatos("Error: Membresía no encontrada con ID: " + idMembresia));

            // Convertir el String del ComboBox a MetodoPago (EFECTIVO, TARJETA, etc.)
            Pago.MetodoPago metodoPago = Pago.MetodoPago.valueOf(metodoPagoSeleccionado.toUpperCase());

            // 3. OBTENER EL MONTO (Se asume que la membresía ya tiene el precio pagado)
            BigDecimal monto = membresiaAPagar.getPrecioPagado(); // Usar el precio calculado en Membresia

            // 4. PROCESAR EL PAGO (Llamada al servicio de negocio)

            // El método en MembresiaService es: 
            // registrarPagoMembresia(Membresia membresia, BigDecimal monto, Pago.MetodoPago metodo, Empleado empleadoRegistro)

            membresiaService.registrarPagoMembresia(
                membresiaAPagar, 
                monto, 
                metodoPago, 
                empleadoEnSesion
            );

            // 5. MOSTRAR ÉXITO Y ACTUALIZAR VISTA
            JOptionPane.showMessageDialog(this, 
                "Pago de $" + monto.toString() + " registrado con éxito para la Membresía " + idMembresia + ".", 
                "Pago Exitoso", 
                JOptionPane.INFORMATION_MESSAGE);

            // Opcional: Limpiar o recargar la vista.

        } catch (ExcepcionDatos ex) {
            // Manejo de errores de validación de negocio
            logger.log(java.util.logging.Level.WARNING, "Error al procesar el pago: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Pago", JOptionPane.WARNING_MESSAGE);

        } catch (Exception ex) {
            // Manejo de errores inesperados (e.g., conversión, I/O)
            logger.log(java.util.logging.Level.SEVERE, "Error inesperado al procesar el pago.", ex);
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al procesar el pago.", "Error del Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonPagarActionPerformed

    private void opMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opMetodoPagoActionPerformed

    private void opClienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opClienteIDActionPerformed
        // TODO add your handling code here:
        // Obtener el ID del cliente seleccionado
        String selectedItem = (String) opClienteID.getSelectedItem();

        // Asumimos que el ID del cliente es el valor completo si no es el elemento por defecto
        if (selectedItem != null && !selectedItem.equals("-- Seleccione Cliente --")) {
            // Cargar las membresías asociadas a este ID
            cargarMembresiasCliente(selectedItem);
        } else {
            // Limpiar el ComboBox de Membresías si no hay un cliente seleccionado
            ((DefaultComboBoxModel<String>) opMembresia.getModel()).removeAllElements();
            ((DefaultComboBoxModel<String>) opMembresia.getModel()).addElement("-- Seleccione Membresía --");
        }
    }//GEN-LAST:event_opClienteIDActionPerformed
    
    private void simularProcesarPago(Membresia membresia, MetodoPago metodo) {
        try {
            // El monto se obtiene de la membresía misma (precio pagado)
            BigDecimal montoAPagar = membresia.getPrecioPagado();

            // El servicio genera el ID de Pago y lo añade al historial
            membresiaService.registrarPagoMembresia(
                membresia, 
                montoAPagar, 
                metodo, 
                empleadoEnSesion
            );

            JOptionPane.showMessageDialog(this, 
                "Pago de " + montoAPagar + " registrado con éxito para membresía " + membresia.getIdMembresia() + ".", 
                "Pago Exitoso", 
                JOptionPane.INFORMATION_MESSAGE);

        } catch (ExcepcionDatos ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al procesar pago", ex);
            JOptionPane.showMessageDialog(this, 
                "Error al procesar el pago: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarClientesID() {
        try {
            // 1. Obtener la lista de todos los clientes
            List<Cliente> clientes = clienteService.getClientes();

            // 2. Obtener el modelo del ComboBox
            // Se asume que opClienteID es un JComboBox<String>
            DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) opClienteID.getModel();

            // 3. Limpiar elementos y agregar un valor predeterminado
            model.removeAllElements();
            model.addElement("-- Seleccione Cliente --"); 

            // 4. Llenar el ComboBox con los IDs
            for (Cliente cliente : clientes) {
                model.addElement(cliente.getIdCliente());
            }

        } catch (Exception e) {
            // En caso de error (e.g., error de lectura de archivo en el servicio)
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar IDs de clientes", e);
            JOptionPane.showMessageDialog(this, 
                "Error al cargar la lista de clientes: " + e.getMessage(), 
                "Error de Datos", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarMembresiasCliente(String idCliente) {
        try {
            // 1. Limpiar el ComboBox de Membresías
            DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) opMembresia.getModel();
            model.removeAllElements();
            model.addElement("-- Seleccione Membresía --");

            // Si el cliente seleccionado es el elemento por defecto, salir
            if (idCliente == null || idCliente.isEmpty() || idCliente.equals("-- Seleccione Cliente --")) {
                return;
            }

            // 2. Buscar el cliente por su ID (usando ClienteService)
            java.util.Optional<Cliente> clienteOpt = clienteService.obtenerClientePorId(idCliente); // Se asume que ClienteService tiene este método

            if (clienteOpt.isPresent()) {
                Cliente cliente = clienteOpt.get();
                // 3. Obtener las membresías del cliente
                List<Membresia> membresias = cliente.getMembresias(); 

                // 4. Llenar el ComboBox con el ID y el nombre de la membresía
                for (Membresia membresia : membresias) {
                    // Formato: [ID Membresía] - [Nombre Tipo] ([Estado/Vigencia])
                    String estado = membresia.estaActiva() ? "Activa" : "Vencida"; // Se asume método estaActiva en Membresia
                    String item = membresia.getIdMembresia() + " - " + membresia.getTipo().getNombre() + " (" + estado + ")"; // Se asume getTipo().getNombre()
                    model.addElement(item);
                }
            } else {
                // Manejar caso donde el ID es válido pero no se encuentra
                JOptionPane.showMessageDialog(this, "Cliente no encontrado.", "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar membresías para el cliente: " + idCliente, e);
            JOptionPane.showMessageDialog(this, "Error al cargar la lista de membresías.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarMetodosPago() {
        // Se asume que opMetodoPago es un JComboBox<String>
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) opMetodoPago.getModel();

        // 1. Limpiar el ComboBox (en caso de que tenga valores por defecto del diseñador)
        model.removeAllElements();

        // 2. Agregar un elemento predeterminado
        model.addElement("-- Seleccione Método --"); 

        // 3. Agregar los métodos de pago deseados
        // NOTA: Los nombres se pueden mostrar en minúsculas y capitalizados para la vista.
        for (Pago.MetodoPago metodo : Pago.MetodoPago.values()) {
            if (metodo == Pago.MetodoPago.EFECTIVO || metodo == Pago.MetodoPago.TARJETA) {
                String nombreFormateado = metodo.name().substring(0, 1).toUpperCase() + 
                                          metodo.name().substring(1).toLowerCase();
                model.addElement(nombreFormateado);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new PagosView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPagar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> opClienteID;
    private javax.swing.JComboBox<String> opMembresia;
    private javax.swing.JComboBox<String> opMetodoPago;
    // End of variables declaration//GEN-END:variables
}
